In [1]:
# Numpy
# Matplotlib
# Pandas
# PIP

In [2]:
# List

In [3]:
# Create a list that store different data types.

In [4]:
# Data Types

In [5]:
arr = [101,"Hello",True,101.2]

In [6]:
# 50P - Sahil

In [7]:
arr = [1,2.5,"hello",True,[3,4,5],{"101":"Ram"},None]

In [8]:
# [3,4,5] - nested list

In [10]:
arr[4]

[3, 4, 5]

In [ ]:
'''
1. int
2. string
3. float
4. boolean
5. list
6. tuple
7. dictionary
8. set
9. NoneType
'''

In [11]:
# In numpy - Object

In [12]:
# Numpy

In [13]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
print(arr1>3)

[False False  True  True]


In [14]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
print(arr1[arr1>3])

[4 5]


In [18]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
res = np.concatenate((arr1,arr2))
print(res)

[2 3 4 5 2 3 4 5]


In [19]:
# concatenate is function

In [20]:
# 50P

In [21]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
res = np.concatenate((arr1[2:],arr2[2:]))
print(res)

[4 5 4 5]


In [22]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
res = np.concatenate((arr1>3,arr2>3))
print(res)

[False False  True  True False False  True  True]


In [23]:
import numpy as np

arr1 = np.array([2,3,4,5])
arr2 = np.array([2,3,4,5])
res = np.concatenate((arr1[arr1>3],arr2[arr2>3]))
print(res)

[4 5 4 5]


In [28]:
import numpy as np


empdata = np.array(
[
    ("Alex",30,60000,"HR"),
    ("Ram",50,160000,"Data Scientist"),
    ("Salmaan",60,50000,"Developer"),
    ("Krish",70,30000,"Analyst"),
    ("Ajay Devgan",40,70000,"HR"),
])

In [29]:
print(empdata)

[['Alex' '30' '60000' 'HR']
 ['Ram' '50' '160000' 'Data Scientist']
 ['Salmaan' '60' '50000' 'Developer']
 ['Krish' '70' '30000' 'Analyst']
 ['Ajay Devgan' '40' '70000' 'HR']]


In [30]:
# 100P

In [31]:
# Display all the employess name of this company.

In [32]:
names = empdata[:,0]
print(names)

['Alex' 'Ram' 'Salmaan' 'Krish' 'Ajay Devgan']


In [33]:
names = empdata[:,1]
print(names)

['30' '50' '60' '70' '40']


In [34]:
names = empdata[0]
print(names)

['Alex' '30' '60000' 'HR']


In [35]:
names = empdata[1]
print(names)

['Ram' '50' '160000' 'Data Scientist']


In [36]:
names = empdata[2]
print(names)

['Salmaan' '60' '50000' 'Developer']


In [37]:
for i in empdata:
    print(i[0])

Alex
Ram
Salmaan
Krish
Ajay Devgan


In [38]:
names = empdata[:1,0]
print(names)

['Alex']


In [39]:
names = empdata[:0,0]
print(names)

[]


In [40]:
names = empdata[:2,0]
print(names)

['Alex' 'Ram']


In [41]:
names = empdata[:3,0]
print(names)

['Alex' 'Ram' 'Salmaan']


In [43]:
names = empdata[:,0] # Extracting the first column(names)
print(names)

['Alex' 'Ram' 'Salmaan' 'Krish' 'Ajay Devgan']


In [44]:
# 100P

In [45]:
# 2. Display the maximum age of the employess

In [46]:
print(max(empdata[:,1]))

70


In [47]:
import numpy as np


empdata = np.array(
[
    ("Alex",30,60000,"HR"),
    ("Ram",50,160000,"Data Scientist"),
    ("Salmaan",60,50000,"Developer"),
    ("Krish",70,30000,"Analyst"),
    ("Ajay Devgan",40,70000,"HR"),
],
dtype=[('name','U10'),('age',int),('salary',float),('department','U15')])

print(empdata)

[('Alex', 30,  60000., 'HR') ('Ram', 50, 160000., 'Data Scientist')
 ('Salmaan', 60,  50000., 'Developer') ('Krish', 70,  30000., 'Analyst')
 ('Ajay Devga', 40,  70000., 'HR')]


In [53]:
print(empdata['name'])

['Alex' 'Ram' 'Salmaan' 'Krish' 'Ajay Devga']


In [54]:
print(empdata['age'])

[30 50 60 70 40]


In [55]:
print(max(empdata['age']))

70


In [56]:
print(type(empdata['age']))

<class 'numpy.ndarray'>


In [57]:
# dtype

In [ ]:
'''
1. It is data type, we are using it here 
'''

In [ ]:
import numpy as np


empdata = np.array(
[
    ("Alex",30,60000,"HR"),
    ("Ram",50,160000,"Data Scientist"),
    ("Salmaan",60,50000,"Developer"),
    ("Krish",70,30000,"Analyst"),
    ("Ajay Devgan",40,70000,"HR"),
],
dtype=[('name','U10'),('age',int),('salary',float),('department','U15')])

print(empdata)

In [58]:
# U10 - Unicode string and 10 is fixed size

In [61]:
import numpy as np


empdata = np.array(
[
    ("Alex",30,60000,"HR"),
    ("Ram",50,160000,"Data Scientist"),
    ("Salmaan",60,50000,"Developer"),
    ("Krish",70,30000,"Analyst"),
    ("Ajay Devgan",40,70000,"HR"),
],
dtype=[('name','U10'),('age',int),('salary',float),('department','U15')])

print(empdata)

[('Alex', 30,  60000., 'HR') ('Ram', 50, 160000., 'Data Scientist')
 ('Salmaan', 60,  50000., 'Developer') ('Krish', 70,  30000., 'Analyst')
 ('Ajay Devga', 40,  70000., 'HR')]


In [63]:
print(empdata['name'][0])

Alex


In [64]:
print(empdata['name'][1])

Ram


In [65]:
print(empdata['name'][2])

Salmaan


In [66]:
# list comprehension

In [67]:
print(empdata['age'][2])

60


In [68]:
print(empdata['department']=='HR')

[ True False False False  True]


In [69]:
print(empdata[empdata['department']=='HR'])

[('Alex', 30, 60000., 'HR') ('Ajay Devga', 40, 70000., 'HR')]


In [71]:
print(empdata['salary'][0])

60000.0


In [72]:
# Find out the total salary paid by the company

In [73]:
print(sum(empdata['salary']))

370000.0


In [78]:
s=sum(empdata[empdata['department']=='HR']['salary'])
s

130000.0

In [ ]:
s=sum(empdata[empdata['department']=='HR']['salary'])

In [81]:
empdata[empdata['department']=='HR']['salary']

array([60000., 70000.])

In [82]:
sum(empdata[empdata['department']=='HR']['salary'])

130000.0

In [87]:
s=np.sum(empdata[empdata['department']=='HR']['salary'])
s

130000.0

* Python Language Basics, 
* OO in Python, 
* Core Python Program Structure, 
* Modules and Exception Handling, 
* Classes in Python, Lists and Tuples, 
* Data Structures and Data Manipulations, 
* Python Generator / Iterators, 
* pip, 
* virtualenv, 
* pythonenv, 
* pep8, 
* Dictionaries, 
* PyTest, 
* Logging and File Handling, 
* Working with Regular Expressions; 
* Working with Pandas etc. 

In [88]:
# What is Virtual Environment?

In [ ]:
'''
1. It is self contained and isolated environment that allow you to
- Install the packages seperately from the global python env.
- Two virtual env, we can install two different packages version
- One VE = can have different python version = 2.7
- Second = python 3.11
- We can work two or more different python version in same system.
- We can work two or more different packages version in same system.
- RTE - College classroom.

'''

In [89]:
'''
1. Zomato - numpy-3.1
2. Flipkart - numpy 2.1
3. It will avoid conflicts.
'''

'\n1. Zomato - numpy-3.1\n2. Flipkart - numpy 2.1\n3. It will avoid conflicts.\n'

In [90]:
# python -m venv india

In [91]:
# india\Scripts\activate

In [92]:
# pip install numpy==1.24